CREATE TABLE IF NOT EXISTS INTEREST_POINTS (
    ID NUMBER(15) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COORDINATE_X NUMBER(15) UNSIGNED NOT NULL,
    COORDINATE_Y NUMBER(15) UNSIGNED NOT NULL,
    PRIMARY KEY(ID)
);

CREATE INDEX COORDINATE_X_IDX ON INTEREST_POINTS(COORDINATE_X);
CREATE INDEX COORDINATE_Y_IDX ON INTEREST_POINTS(COORDINATE_Y);